export const LANGUAGES: { code: string; name: string; nativeName: string; currencySymbol: string }[] = [
  { code: "en", name: "English", nativeName: "English", currencySymbol: "$" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", currencySymbol: "₹" },
  { code: "es", name: "Spanish", nativeName: "Español", currencySymbol: "€" },
  { code: "fr", name: "French", nativeName: "Français", currencySymbol: "€" },
  { code: "de", name: "German", nativeName: "Deutsch", currencySymbol: "€" },
  { code: "ar", name: "Arabic", nativeName: "العربية", currencySymbol: "﷼" },
  { code: "zh-CN", name: "Chinese (Simplified)", nativeName: "简体中文", currencySymbol: "¥" },
  { code: "zh-TW", name: "Chinese (Traditional)", nativeName: "繁體中文", currencySymbol: "NT$" },
  { code: "ja", name: "Japanese", nativeName: "日本語", currencySymbol: "¥" },
  { code: "ko", name: "Korean", nativeName: "한국어", currencySymbol: "₩" },
  { code: "pt", name: "Portuguese", nativeName: "Português", currencySymbol: "€" },
  { code: "ru", name: "Russian", nativeName: "Русский", currencySymbol: "₽" },
  { code: "it", name: "Italian", nativeName: "Italiano", currencySymbol: "€" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", currencySymbol: "€" },
  { code: "pl", name: "Polish", nativeName: "Polski", currencySymbol: "zł" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", currencySymbol: "₺" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", currencySymbol: "₫" },
  { code: "th", name: "Thai", nativeName: "ไทย", currencySymbol: "฿" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", currencySymbol: "Rp" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu", currencySymbol: "RM" },
  { code: "fa", name: "Persian", nativeName: "فارسی", currencySymbol: "﷼" },
  { code: "ur", name: "Urdu", nativeName: "اردو", currencySymbol: "₨" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", currencySymbol: "৳" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", currencySymbol: "₹" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", currencySymbol: "₹" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", currencySymbol: "₹" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", currencySymbol: "₹" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", currencySymbol: "₹" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", currencySymbol: "₹" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", currencySymbol: "₹" },
  { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ", currencySymbol: "₹" },
  { code: "as", name: "Assamese", nativeName: "অসমীয়া", currencySymbol: "₹" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली", currencySymbol: "Rs" },
  { code: "si", name: "Sinhala", nativeName: "සිංහල", currencySymbol: "Rs" },
  { code: "my", name: "Burmese", nativeName: "မြန်မာ", currencySymbol: "K" },
  { code: "km", name: "Khmer", nativeName: "ខ្មែរ", currencySymbol: "៛" },
  { code: "lo", name: "Lao", nativeName: "ລາວ", currencySymbol: "₭" },
  { code: "he", name: "Hebrew", nativeName: "עברית", currencySymbol: "₪" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili", currencySymbol: "KSh" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ", currencySymbol: "Br" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá", currencySymbol: "₦" },
  { code: "ig", name: "Igbo", nativeName: "Igbo", currencySymbol: "₦" },
  { code: "ha", name: "Hausa", nativeName: "Hausa", currencySymbol: "₦" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu", currencySymbol: "R" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa", currencySymbol: "R" },
  { code: "af", name: "Afrikaans", nativeName: "Afrikaans", currencySymbol: "R" },
  { code: "sq", name: "Albanian", nativeName: "Shqip", currencySymbol: "L" },
  { code: "hy", name: "Armenian", nativeName: "Հայերեն", currencySymbol: "֏" },
  { code: "az", name: "Azerbaijani", nativeName: "Azərbaycan", currencySymbol: "₼" },
  { code: "eu", name: "Basque", nativeName: "Euskara", currencySymbol: "€" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская", currencySymbol: "Br" },
  { code: "bg", name: "Bulgarian", nativeName: "Български", currencySymbol: "лв" },
  { code: "ca", name: "Catalan", nativeName: "Català", currencySymbol: "€" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski", currencySymbol: "€" },
  { code: "cs", name: "Czech", nativeName: "Čeština", currencySymbol: "Kč" },
  { code: "da", name: "Danish", nativeName: "Dansk", currencySymbol: "kr" },
  { code: "eo", name: "Esperanto", nativeName: "Esperanto", currencySymbol: "€" },
  { code: "et", name: "Estonian", nativeName: "Eesti", currencySymbol: "€" },
  { code: "tl", name: "Filipino", nativeName: "Filipino", currencySymbol: "₱" },
  { code: "fi", name: "Finnish", nativeName: "Suomi", currencySymbol: "€" },
  { code: "gl", name: "Galician", nativeName: "Galego", currencySymbol: "€" },
  { code: "ka", name: "Georgian", nativeName: "ქართული", currencySymbol: "₾" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά", currencySymbol: "€" },
  { code: "ht", name: "Haitian Creole", nativeName: "Kreyòl Ayisyen", currencySymbol: "G" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar", currencySymbol: "Ft" },
  { code: "is", name: "Icelandic", nativeName: "Íslenska", currencySymbol: "kr" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge", currencySymbol: "€" },
  { code: "kk", name: "Kazakh", nativeName: "Қазақша", currencySymbol: "₸" },
  { code: "rw", name: "Kinyarwanda", nativeName: "Ikinyarwanda", currencySymbol: "FRw" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча", currencySymbol: "с" },
  { code: "lv", name: "Latvian", nativeName: "Latviešu", currencySymbol: "€" },
  { code: "lt", name: "Lithuanian", nativeName: "Lietuvių", currencySymbol: "€" },
  { code: "lb", name: "Luxembourgish", nativeName: "Lëtzebuergesch", currencySymbol: "€" },
  { code: "mk", name: "Macedonian", nativeName: "Македонски", currencySymbol: "ден" },
  { code: "mg", name: "Malagasy", nativeName: "Malagasy", currencySymbol: "Ar" },
  { code: "mt", name: "Maltese", nativeName: "Malti", currencySymbol: "€" },
  { code: "mi", name: "Maori", nativeName: "Māori", currencySymbol: "$" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол", currencySymbol: "₮" },
  { code: "no", name: "Norwegian", nativeName: "Norsk", currencySymbol: "kr" },
  { code: "ps", name: "Pashto", nativeName: "پښتو", currencySymbol: "؋" },
  { code: "ro", name: "Romanian", nativeName: "Română", currencySymbol: "lei" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Sāmoa", currencySymbol: "WS$" },
  { code: "gd", name: "Scots Gaelic", nativeName: "Gàidhlig", currencySymbol: "£" },
  { code: "sr", name: "Serbian", nativeName: "Српски", currencySymbol: "дин" },
  { code: "sn", name: "Shona", nativeName: "chiShona", currencySymbol: "$" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي", currencySymbol: "₨" },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina", currencySymbol: "€" },
  { code: "sl", name: "Slovenian", nativeName: "Slovenščina", currencySymbol: "€" },
  { code: "so", name: "Somali", nativeName: "Soomaali", currencySymbol: "Sh" },
  { code: "su", name: "Sundanese", nativeName: "Basa Sunda", currencySymbol: "Rp" },
  { code: "sv", name: "Swedish", nativeName: "Svenska", currencySymbol: "kr" },
  { code: "tg", name: "Tajik", nativeName: "Тоҷикӣ", currencySymbol: "SM" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська", currencySymbol: "₴" },
  { code: "uz", name: "Uzbek", nativeName: "O'zbek", currencySymbol: "soʻm" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg", currencySymbol: "£" },
  { code: "yi", name: "Yiddish", nativeName: "ייִדיש", currencySymbol: "$" },
];
